#!/usr/bin/env python

import asyncio
import argparse

from server import EchoServer, BroadcastServer, GSetServer, GCounterServer

parser = argparse.ArgumentParser(description="Maelstrom test server")
parser.add_argument("-w", "--workload", choices=[
    "echo",
    "broadcast",
    "g-set",
    "g-counter",
])
args = parser.parse_args()

server = None
if args.workload == "echo":
    server = EchoServer()
if args.workload == "broadcast":
    server = BroadcastServer()
if args.workload == "g-set":
    server = GSetServer()
if args.workload == "g-counter":
    server = GCounterServer()

asyncio.run(server.run())
