#!/usr/bin/env python

import argparse

from server import (
    EchoServer,
    BroadcastServer,
    GSetServer,
    GCounterServer,
    PNCounterServer,
    TxnServer,
)

parser = argparse.ArgumentParser(description="Maelstrom test server")
parser.add_argument("-w", "--workload", choices=[
    "echo",
    "broadcast",
    "g-set",
    "g-counter",
    "pn-counter",
    "txn",
])
args = parser.parse_args()

server = None
if args.workload == "echo":
    server = EchoServer()
if args.workload == "broadcast":
    server = BroadcastServer()
if args.workload == "g-set":
    server = GSetServer()
if args.workload == "g-counter":
    server = GCounterServer()
if args.workload == "pn-counter":
    server = PNCounterServer()
if args.workload == "txn":
    server = TxnServer()
if not server:
    raise Exception("Unknown workload {!r}".format(args.workload))

server.run()
